<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ngt" nsURI="http://qualab.jp/vstep/" nsPrefix="ngt">
  <eClassifiers xsi:type="ecore:EClass" name="ViewPoint" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifierViewPoint" eSuperTypes="#//ViewPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testCasesNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualityRisk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coverage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationViewPoint" abstract="true" eSuperTypes="#//ViewPoint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inheritance" eSuperTypes="#//RelationViewPoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superClass" lowerBound="1"
        eType="#//ClassifierViewPoint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subClass" lowerBound="1"
        eType="#//ClassifierViewPoint" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
